import Box from '@mui/material/Box';
import Head from 'next/head'
import Typography from '@mui/material/Typography'

const Layout = ({children , title}: any) => {

  return (
    <>
      <Head>
        <title>Challenge | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;800&display=swap" rel="stylesheet" />
      </Head>
      <Box my={5} mx='auto' textAlign='center' maxWidth='85%' >
        <Typography color="#424242" fontWeight='bold' variant='h2'>
          <Box display='inline-block' color='#FF452B'>Houm</Box> challenge 
        </Typography>
        { children }
      </Box>
    </>
  )
}

export default Layout;